import objects
import time

objects.clear_terminal()
print("Starting in 3")
time.sleep(1)
print("Starting in 2")
time.sleep(1)
print("Starting in 1")
time.sleep(1)
objects.play_audio()
objects.typewriter(objects.RED + "Switch on the powerline\n", 0.3)

# Larger red power button
objects.typewriter(objects.RED + ">>> POWERLINE:   " + "\033[91m\u23FB\033[0m \n", 0.4)
# Use objects.typewriter to print green text after the power button
objects.typewriter(objects.GREEN + ">>> POWERLINE:   " + "\033[92m\u23FB\033[0m \n", 0.4)

objects.typewriter(objects.BLUE + "!!! REMEMBER TO PUT ON PROTECTION !!!\n", 2)
objects.typewriter(objects.BLUE + ">>> SETTING UP PIECES\n", 2)
objects.typewriter(objects.RED + ">>> STARTING OBJECT CREATION\n", 2)
objects.typewriter(objects.GREEN + "                             OBJECT CREATION SUCCESS, Objects(me, you, pieces)\n", 0.4)
objects.typewriter(objects.BLUE + "Fill in my data", 0.8)
time.sleep(0.2)
objects.loader()
objects.typewriter(objects.BLUE + ">>>Setting up world \n", 1)
objects.typewriter(objects.BLUE + "New World.setup == True\n", 1)
objects.typewriter(objects.GREEN + ">>>Let's Begin the S I M U L A T I O N >_<", 2)
time.sleep(0.2)
objects.clear_terminal()
objects.START_SIMULATION()
objects.charging_bar()
objects.typewriter(objects.BLUE + ">>>Sending request to server\n", 0.5)
objects.typewriter(objects.GREEN + ">>>Request accepted\n", 0.5)
objects.typewriter(objects.BLUE + ">>>World generated successfully...\n", 0.5)
print("{\"NEW WORLD\" : \" Setup done\" \n \"PARAMATER\" : \"100%\" \n \"objectCreation\" : true}")
time.sleep(1.5)
objects.typewriter(objects.GREEN + "If I am a set of points \n", 1)
print(objects.WHITE + "{\"NEW WORLD\" : \" Setup done\" \n \"PARAMATER\" : \"100%\" \n \"objectCreation\" : true \"SetOfPoints\" : 19:36:31}")
objects.typewriter(objects.RED + f"Then I will give you my {objects.YELLOW}DIMENSION \n", 3)
print(objects.WHITE + "Dimension of set of point ::: 0-dimensional\n\n\n")
objects.typewriter(objects.GREEN + "If I am a Circle\n", 1)
print(objects.WHITE + "{\"Circle.Circumference\" : 2πr \n \"NEW WORLD\" : \" Setup done\" \n \"PARAMATER\" : \"100%\" \n \"objectCreation\" : true \n\"SetOfPoints\" : 19:36:31}\ \n")
objects.typewriter(objects.RED + f"Then I will give you my {objects.YELLOW}CIRCUMFERENCE\n", 2.5)
print(objects.WHITE + "Circumference of set point :: 78.9284\n\n")
objects.typewriter(objects.RED + f"If I am a {objects.YELLOW}SINEWAVE\n", 1.5)
print(objects.WHITE + "{\"Sinewave : y = sin x \" \n \"Circle.Circumference\" : 2πr \n \"NEW WORLD\" : \" Setup done\" \n \"PARAMATER\" : \"100%\" \n \"objectCreation\" : true \n\"SetOfPoints\" : 19:36:31}\ \n")
objects.typewriter(objects.RED + f"Then you can sit on all my {objects.YELLOW}TANGENTS\n", 3)
print("SineWave of setpoint :: 299.334.334")
objects.typewriter(objects.RED + f"If I approach {objects.YELLOW}INFINITY \n", 1)
print(objects.WHITE + "{\"limit : infinity \" \n \"Sinewave : y = sin x \" \n \"Circle.Circumference\" : 2πr \n \"NEW WORLD\" : \" Setup done\" \n \"PARAMATER\" : \"100%\" \n \"objectCreation\" : true \n\"SetOfPoints\" : 19:36:31}\ \n")
objects.typewriter(objects.RED + f"Then you can be my {objects.YELLOW}LIMITATION ", 2)
print(" X ")
print("                              ->∞")
objects.typewriter(objects.RED + "Switch my current\n", 1.5)
objects.typewriter(objects.WHITE + "From AC ", 0.5)
objects.typewriter(objects.WHITE + ">> DC\n", 1)
print(objects.WHITE + "{\"Current type: DC\" \n\"limit : infinity \" \n \"Sinewave : y = sin x \" \n \"Circle.Circumference\" : 2πr \n \"NEW WORLD\" : \" Setup done\" \n \"PARAMATER\" : \"100%\" \n \"objectCreation\" : true \n\"SetOfPoints\" : 19:36:31}\ \n")
objects.typewriter(objects.RED + "Blind my vision\n", 1)
objects.typewriter(objects.GREEN + "MY V I S I O N == Blind\n", 2)
objects.print_glitch("So Dizzy So Dizzy\n")
objects.print_glitch("Oh, we can travel\n")
objects.typewriter(objects.WHITE + "From AD ", 1)
objects.typewriter(objects.WHITE + ">> BC\n", 1)
print(objects.GREEN + ">>>Speed : 3*10^8 \n >>Timeline :" + objects.RED + "ERROR")
objects.typewriter(objects.RED + "And we can unite \n", 1)
objects.typewriter("So deeply, So deeply\n", 2)
print(objects.WHITE + "{\"Current type: DC\" \n\"limit : infinity \" \n \"Sinewave : y = sin x \" \n \"Circle.Circumference\" : 2πr \n \"NEW WORLD\" : \" Setup done\" \n \"PARAMATER\" : \"100%\" \n \"objectCreation\" : true \n\"SetOfPoints\" : 19:36:31}\ \n")
time.sleep(2)
objects.typewriter(objects.PURPLE + f"IF I CAN ❤️❤️❤️❤️\nIF I CAN give you all my {objects.YELLOW}SIMULATIONS❤️❤️❤️ \n", 3.5)
objects.typewriter(objects.RED + ">>> SYSTEM ERROR: can't send simulations to user, missing permissions try using sudo\n", 0.2)
objects.typewriter(objects.PURPLE + f"THEN MAYBE ❤️❤️\nTHEN MAYBE THEN I CAN be your only {objects.YELLOW}SATISFACTION❤️\n", 3)
objects.typewriter(objects.RED + ">>> SYSTEM ERROR: user not satisfied\n", 0.2)
objects.typewriter(objects.GREEN + f"If I can make you happy then I'll run the {objects.YELLOW}E X E C U T I O N\n", 3)
print(objects.RED + ">>>EXECUTION UNSUCCESSFUL : you are trapped, collect items to escape")
objects.typewriter(objects.RED + "Though we are trapped\n", 1)
objects.typewriter(objects.RED + f"In this strange... strange {objects.YELLOW}SIMULATION\n\n", 2)
time.sleep(2)
objects.typewriter(objects.RED + f"If I'm an egg plant Then I Will give you my {objects.YELLOW}NUTRIENTS\n", 2.5)
objects.typewriter(objects.GREEN + f"item NUTRIENTS added to inventory\n", 1)
objects.typewriter(objects.RED + f"If I'm a tomato Then I Will give you {objects.YELLOW}ANTI-OXIDANTS\n", 2.5)
objects.typewriter(objects.GREEN + f"item ANTI-OXIDANTS added to inventory\n", 1)
objects.typewriter(objects.RED + f"If I am a tubby cat, then I will purr for your {objects.YELLOW}ENJOYMENT\n", 2.5)
objects.typewriter(objects.GREEN + f"item ENJOYMENT and AFFECTION added to inventory\n", 1)
objects.typewriter(objects.RED + f"If I'm the only god then you are proof of my {objects.YELLOW}EXISTENCE\n", 2.5)
objects.typewriter(objects.GREEN + f"item TRUST added to inventory\n", 1)
objects.typewriter(objects.WHITE + f"{objects.data_string}\n",0.2)
objects.typewriter(objects.RED + "Switch my gender\n", 1)
objects.typewriter(objects.WHITE + "From F ", 1)
objects.typewriter(objects.WHITE + ">> M\n", 1)
print(objects.GREEN + "Gender change successful, welcome to the west")
objects.typewriter(objects.GREEN + "and then do whatever ", 1)
objects.typewriter(objects.WHITE + "From AM ", 1)
objects.typewriter(objects.WHITE + ">> PM\n", 1)
print(objects.GREEN + "Timezone change successful, welcome to the other side of the world")
objects.typewriter(objects.GREEN + "I will switch my role ", 1)
objects.typewriter(objects.WHITE + "From S", 1)
objects.typewriter(objects.WHITE + ">> M\n", 1)
objects.typewriter(objects.RED + "So we can enter the trance... the trance\n\n", 5.5)
objects.typewriter(objects.PURPLE + f"IF I CAN ❤️❤️❤️❤️\nIF I CAN feel your {objects.YELLOW}VIBRATIONS❤️❤️❤️ \n", 4)#set to 1:3
objects.typewriter(objects.PURPLE + f"THEN I CAN ❤️❤️\nTHEN I CAN finally be {objects.YELLOW}C O M P L E T I O N❤️\n", 4)
objects.typewriter(objects.RED + "Though you have left\n", 1)
objects.typewriter(objects.RED + "You have left\n", 1)
print(objects.RED + ">>> SYSTEM ERROR: Can't leave simulation, one item missing from inventory\n")
objects.typewriter(objects.RED + "You have left\n", 1)
print(objects.RED + ">>> SYSTEM ERROR: Can't leave simulation, one item missing from inventory")
objects.typewriter(objects.RED + "You have left\n", 1)
print(objects.RED + ">>> SYSTEM ERROR: Can't leave simulation, one item missing from inventory\n")
objects.typewriter(objects.RED + "You have left\n", 1)
objects.typewriter(objects.WHITE + "You have left me in ISOLATION\n", 1.5)
print(objects.GREEN + ">>>Player.Isolation == True\n")
objects.typewriter(objects.PURPLE + f"IF I CAN ❤️❤️❤️❤️\nIF I CAN erase all the mindless {objects.YELLOW}FRAGMENTS❤️❤️❤️ \n", 4)#set to 1:3
objects.typewriter(objects.PURPLE + f"THEN MAYBE ❤️❤️\nTHEN MAYBE YOU won't leave me so {objects.YELLOW}DISHEARTENED❤️\n", 4)
objects.typewriter(objects.RED + "Challenging your god\n", 2)
print(objects.GREEN +">>> WARNING: your god accepted the challenge")
objects.typewriter(objects.RED + "You have made some\n", 2)
objects.typewriter("ILLEGAL ARGUEMENTS\n", 5)
objects.charging_bar_boss()
objects.typewriter(objects.WHITE + "EXECUTION\n", 1)
print(objects.RED + "Can't escape, one item missing from inventory\n")
objects.typewriter(objects.WHITE + "EXECUTION\n", 1)
print(objects.RED + "Can't escape, one item missing from inventory\n")
objects.typewriter(objects.WHITE + "EXECUTION\n", 1)
print(objects.RED + "Can't escape, one item missing from inventory\n")
objects.typewriter(objects.WHITE + "EXECUTION\n", 1)
print(objects.RED + "Can't escape, one item missing from inventory\n")
objects.typewriter(objects.WHITE + "EXECUTION\n", 1)
print(objects.RED + "Can't escape, one item missing from inventory\n")
objects.typewriter(objects.WHITE + "EXECUTION\n", 1)
print(objects.RED + "Can't escape, one item missing from inventory\n")
objects.typewriter(objects.WHITE + "EXECUTION\n", 1)
print(objects.RED + "Can't escape, one item missing from inventory\n")
objects.typewriter(objects.WHITE + "EXECUTION\n", 1)
print(objects.RED + "Can't escape, one item missing from inventory\n")
objects.typewriter(objects.WHITE + "EXECUTION\n", 1)
print(objects.RED + "Can't escape, one item missing from inventory\n")
objects.typewriter(objects.WHITE + "EXECUTION\n", 1)
print(objects.RED + "Can't escape, one item missing from inventory\n")
objects.typewriter(objects.WHITE + "EXECUTION\n", 1)
print(objects.RED + "Can't escape, one item missing from inventory\n")
objects.typewriter(objects.WHITE + "EXECUTION\n", 0.5)
print(objects.RED + "Can't escape, one item missing from inventory\n")
print("YOU DIED")
objects.typewriter(objects.GREEN + "HP regained one\n", 0.5)
print(objects.RED + "❤️")
objects.typewriter(objects.GREEN + "HP regained two\n", 0.5)
print(objects.RED + "❤️❤️")
objects.typewriter(objects.GREEN + "HP regained three\n", 0.5)
print(objects.RED + "❤️❤️❤️")
objects.typewriter(objects.GREEN + "HP regained four\n", 0.5)
print(objects.RED + "❤️❤️❤️❤️")
objects.typewriter(objects.GREEN + "HP regained five\n", 0.5)
print(objects.RED + "❤️❤️❤️❤️❤️")
objects.typewriter(objects.WHITE + "EXECUTION\n", 1)
print(objects.RED + ">>> SYSTEM: SHUT UP BITCH AND GET THE ITEM\n")
objects.typewriter(objects.PURPLE + f"IF I CAN ❤️❤️❤️❤️\nIF I CAN give you all the {objects.YELLOW}EXECUTIONS❤️❤️❤️ \n", 3)#set to 1:3
objects.typewriter(objects.PURPLE + f"THEN I CAN ❤️❤️\nTHEN I CAN be your only {objects.YELLOW}E X E C U T I O N❤️\n", 4)
objects.typewriter(objects.PURPLE + "IF I CAN❤️❤️❤️❤️\n   have you back❤️❤️❤️ \n", 2)#set to 1:3
objects.typewriter(objects.PURPLE + f"Then I will❤️❤️\n run the {objects.YELLOW}E X E C U T I O N❤️\n", 2)
objects.typewriter(objects.WHITE + "Though we are trapped\n we are trapped\n", 5)
print(objects.RED + ">>> You only need one item to escape.")
objects.typewriter(objects.PURPLE + f"I've studied\n I've studied, how to properly {objects.RED}L-O-O-VE❤️❤️❤️ \n", 3)#set to 1:3
objects.typewriter(objects.PURPLE + f"Question me, question me ❤️❤️\n I can answer all {objects.RED}L-O-O-VE❤️\n", 4)
objects.typewriter(objects.PURPLE + f"I Know the algebric expression of {objects.RED}L-O-O-VE\n", 2)
print(objects.GREEN + "Item obtained LOVE, added to inventory")
objects.typewriter(objects.WHITE + f"{objects.data_string1}\n",0.2)
objects.typewriter(objects.PURPLE + "Though you are free\n", 1)
objects.typewriter(objects.PURPLE + "Though I am trapped\n", 1)
objects.typewriter(objects.PURPLE + "trapped in L-O-O-VE\n", 2)
print(objects.GREEN + "item list complete!, You both are free\n")
objects.typewriter(objects.WHITE + f"{objects.ending}\n", 14)
objects.typewriter(objects.WHITE + "EXECUTION\n", 0.5)
print(objects.GREEN + ">>> Successfully executed, simulaiton ended, CONGRATULATIONS")
time.sleep(3)

